{
 "title": "ZIO Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ZIO Demo CountAll",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(countAll[1m])", "legendFormat": "count / sec" }
   ]
  },
  {
   "title": "ZIO Fiber Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "zio_fiber_started", "legendFormat": "Fibers started" },
    { "expr": "zio_fiber_successes", "legendFormat": "Fibers succeeded" }
   ]
  },
  {
   "title": "ZIO Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "mySummary", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "ZIO fiber fork locations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zio_fiber_fork_locations", "legendFormat": "{{bucket}}" }
   ]
  },
  {
   "title": "ZIO Sample Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "myHistogram_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "JVM Current Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "ZIO Sample Set",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mySet", "legendFormat": "{{bucket}}" }
   ]
  },
  {
   "title": "JVM memory bytes used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}}" }
   ]
  },
  {
   "title": "ZIO Gauges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "gauge1", "legendFormat": "{{id}}" },
    { "expr": "gauge2" }
   ]
  }
 ]
}